language: node_js
node_js:
- 6.3.1
notifications:
  slack:
    secure: IP6yNsO366Zd396vxtc1nn+hqBagecUrzi+kdDFqffMDsaiBNTwo2kxamueMcx55wpbInzAvC3/kCP6QLsA0451nTaP2BCJP4A40L1FCYT+OeVDpakUJlucdA+Rl44jWG0ZqRFAyd2uVECVBfAkzd+nRCIns3t9q15FKmUWjFvol0VT79SbXI5cHppJiiOxeVeg0ojierP9zpmQXEJ+7DXKcWDtvygWILQFRnGjd72PYlTZQabQh0dlZBpWpA6rjxoFNa5/SG/UeoC6SY2vDzS5NZI0V8wiv+/PgncSQIWC0u2apsBwekF98No2X7wnFGV2GO2irk6c0NWbHk6A8UY7oDkxskUod3XQhWV80m6B3ASsCSrm2ggSP5YQbqF+pHIHLO9H+ZmiDNL+Mzv2JFsyOBU2DTe83DmKGThsBSaC8S5B42CZkSSbZb86OfwMZKQiRpGjH3pFU/Y1GeWOAq91D74cSBznpCEwlBo5IDVGYHbYDdKQkEbs7xi/T3HSQFLXaqIHa2leGDDZbyzRPGMlUJFqJEYRJQyCXaDgho+pcEYRZBOo3ZQ+KuI2vtGo8P0W7ooGYYXflkE3q1+z1GNzd7IqfO5Sum3n3lTi7+tGkKkjVykIDoEBHK/teUjBF4M21MAWAj9CuaPgm2VAgCa0c1d+r8rKK9mC0zJwcHXc=
